name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v --triple x86_64-apple-ios15.0-simulator

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: swift test -v --enable-test-discovery --destination 'platform=iOS Simulator,name=iPhone 13'
